import Image from "next/image";
import { notFound } from "next/navigation";
import ids from "../../../data/idsOnSell.json";
import ShareButton from "./ShareButton";

type PageProps = {
  params: Promise<{ slug: string }>;
};

export default async function Page({ params }: PageProps) {
  const { slug } = await params;
  const item: any = ids.find((i) => i.slug === slug);
  if (!item) notFound();

  const siteUrl = "https://bluebuff.in";
  const rent = item.rent;

  const shareText = `🔥 MLBB Account For Sale

${item.title}

🎭 Heroes: ${item.heroes.total}+
🎨 Skins: ${item.skins.total}+
💎 COA: ${item.currencies.coa}+
🌍 Global Heroes: ${item.heroTitles.global.length}

Price: ₹${item.price}

Generated by bluebuff.in`;

  return (
    <main className="min-h-screen max-w-6xl mx-auto px-4 py-12 space-y-12 text-[var(--foreground)]">

      {/* ================= TOP UTILITY (SHARE) ================= */}
      <div className="flex justify-end">
        <div
          className="
            flex items-center gap-2
            px-3 py-2 rounded-lg
            text-sm text-[var(--muted)]
            hover:text-[var(--foreground)]
            hover:bg-white/5 transition
          "
        >
          <ShareButton
            text={shareText}
            url={`${siteUrl}/idsonsell/${item.slug}`}
          />
        </div>
      </div>

      {/* ================= HERO ================= */}
      <section className="rounded-3xl overflow-hidden bg-[var(--card)] border border-[var(--border)]">
        <div className="relative h-[320px]">
          <Image
            src={item.media?.images?.[0] || item.media?.fallbackImage}
            alt={item.title}
            fill
            className="object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/60 to-transparent" />
        </div>

        <div className="p-6 space-y-4">
          <div className="flex items-center gap-3 flex-wrap">
            <h1 className="text-3xl font-bold">{item.title}</h1>
            {item.meta?.verifiedByAdmin && (
              <span className="text-xs px-2 py-1 rounded-full bg-emerald-500/15 text-emerald-400">
                Verified
              </span>
            )}
          </div>

          <div className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-[var(--muted)]">
            <span>
              Server: <b className="text-[var(--foreground)]">{item.account.server}</b>
            </span>
            <span>
              Login: <b className="text-[var(--foreground)]">{item.account.loginType}</b>
            </span>
            <span>
              Account Age:{" "}
              <b className="text-[var(--foreground)]">
                {item.account.accountAgeYears} yrs
              </b>
            </span>
            <span>
              Rebindable:{" "}
              <b
                className={
                  item.account.rebindable
                    ? "text-emerald-400"
                    : "text-red-400"
                }
              >
                {item.account.rebindable ? "Yes" : "No"}
              </b>
            </span>
          </div>
          <div className="flex flex-wrap gap-x-6 gap-y-2 text-sm text-[var(--muted)]">
            <span>
              collection: <b className="text-[var(--foreground)]">{item.collection.points}</b>
            </span>
            <span>
              <b className="text-[var(--foreground)]">{item.collection.tier}</b>
            </span>

          </div>
        </div>
      </section>

      {/* ================= BUY / RENT ================= */}
      <section className="grid sm:grid-cols-2 gap-6">
        <div className="glass rounded-2xl p-6 border border-[var(--border)] space-y-3">
          <span className="text-xs uppercase tracking-wide text-[var(--muted)]">
            Buy Account
          </span>
          <div className="text-3xl font-bold text-[var(--accent)]">
            ₹{item.price}
          </div>
          <p className="text-sm text-[var(--muted)]">
            Permanent ownership • Full access
          </p>
          <p className="text-xs text-[var(--muted)]">
            Status:{" "}
            <b className="text-[var(--foreground)]">
              {item.availability.status}
            </b>{" "}
            • Hold:{" "}
            <b className="text-[var(--foreground)]">
              {item.availability.holdAllowed ? "Allowed" : "No"}
            </b>
          </p>
        </div>

        {rent?.available && (
          <div className="glass rounded-2xl p-6 border border-emerald-400/30 bg-emerald-500/5 space-y-3">
            <span className="text-xs uppercase tracking-wide text-emerald-400">
              Rent (24 Hours)
            </span>
            <div className="text-2xl font-bold text-emerald-400">
              ₹{rent.price}
            </div>
            <ul className="text-sm text-emerald-200 list-disc ml-4 space-y-1">
              {rent.conditions.map((c: string, i: number) => (
                <li key={i}>{c}</li>
              ))}
            </ul>
          </div>
        )}
      </section>

      {/* ================= HIGHLIGHTS ================= */}
      <section className="glass rounded-2xl p-6 border border-[var(--border)]">
        <h2 className="font-semibold mb-3">Highlights</h2>
        <div className="flex flex-wrap gap-2">
          {item.highlights.map((h: string, i: number) => (
            <span
              key={i}
              className="px-3 py-1 text-xs rounded-full bg-white/5"
            >
              {h}
            </span>
          ))}
        </div>
      </section>

      {/* ================= DETAILS ================= */}
      <section className="grid md:grid-cols-2 gap-6">

        <Card title="Rank">
          <Info label="Current" value={item.rank.current} />
          <Info label="Highest" value={item.rank.highest} />
          <Info label="Stars" value={item.rank.stars} />
        </Card>

        <Card title="Collection">
          <Info label="Tier" value={item.collection.tier} />
          <Info label="Points" value={item.collection.points} />
        </Card>

        <div className="glass rounded-2xl p-6 border border-[var(--border)] md:col-span-2">
          <h2 className="font-semibold mb-4">Skins Breakdown</h2>
          <div className="grid sm:grid-cols-3 gap-6 text-sm">
            <SkinList title="Legend" items={item.skins.legendList} />
            <SkinList title="Grand" items={item.skins.grandList} />
            <SkinList title="Exquisite" items={item.skins.exquisiteList} />

            <SkinList title="Collector" items={item.skins.collector} />
            <SkinList title="Rare" items={item.skins.rare} />
          </div>
        </div>

        <Card title="Currencies">
          <Info label="COA" value={item.currencies.coa} />
          <Info label="Magic Core" value={item.currencies.magicCore} />
          <Info
            label="Double Diamonds"
            value={item.diamonds.doubleDiamondAvailable.join(", ")}
          />
          <Info label="Balance" value={item.diamonds.balance} />
        </Card>

        <Card title="Cosmetics">
          {item.cosmetics.epicRecall && <Check text="Epic Recall" />}
          {item.cosmetics.exclusiveRecalls && <Check text="Exclusive Recalls" />}
          {item.cosmetics.exclusiveSpawnEffects && <Check text="Spawn Effects" />}
          {item.cosmetics.exclusiveEliminationEffects && (
            <Check text="Elimination Effects" />
          )}
        </Card>

        <div className="glass rounded-2xl p-6 border border-[var(--border)] md:col-span-2">
          <h2 className="font-semibold mb-3">Hero Titles</h2>
          <ul className="text-sm space-y-1">
            {item.heroTitles.global.map((g: any, i: number) => (
              <li key={i}>🌍 {g.hero} — {g.rank}</li>
            ))}
          </ul>
          <p className="text-sm mt-3">
            Supreme: <b>{item.heroTitles.supreme.join(", ")}</b>
          </p>
        </div>

        <div className="glass rounded-2xl p-6 border border-[var(--border)] md:col-span-2">
          <h2 className="font-semibold mb-3">Additional Features</h2>
          <div className="grid sm:grid-cols-2 gap-2 text-sm">
            {item.others.map((o: any, i: number) => (
              <div key={i}>
                {o.key}: <b>{o.value}</b>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ================= CONTACT ================= */}
      <a
        href={item.dealer.contact.whatsapp}
        target="_blank"
        rel="noopener noreferrer"
        className="
          flex items-center justify-between
          px-5 py-4 rounded-xl
          bg-white/5 border border-[var(--border)]
          hover:border-[var(--accent)] hover:bg-white/10 transition
        "
      >
        <span className="font-medium">
          Contact Dealer{" "}
          <span className="text-[var(--muted)]">
            ({item.dealer.owner})
          </span>
        </span>
        <span className="text-sm text-[var(--accent)]">WhatsApp →</span>
      </a>

      <p className="text-xs text-center text-[var(--muted)]">
        Account ID: {item.id} • Created {item.meta.createdAt} • Updated{" "}
        {item.meta.updatedAt}
      </p>
    </main>
  );
}

/* ================= HELPERS ================= */

function Card({ title, children }: any) {
  return (
    <div className="glass rounded-2xl p-6 border border-[var(--border)] space-y-2">
      <h2 className="font-semibold mb-2">{title}</h2>
      {children}
    </div>
  );
}

function Info({ label, value }: any) {
  return (
    <p className="text-sm text-[var(--muted)]">
      {label}: <b className="text-[var(--foreground)]">{value}</b>
    </p>
  );
}

function Check({ text }: any) {
  return <p className="text-sm">✔ {text}</p>;
}

function SkinList({ title, items }: any) {
  return (
    <div>
      <b className="block mb-2">{title}</b>
      <ul className="space-y-1">
        {items.map((s: string, i: number) => (
          <li key={i}>• {s}</li>
        ))}
      </ul>
    </div>
  );
}
