import { BlogPost } from "./types";

export const GENSHIN_BLOGS_DATA: BlogPost[] = [
    {
        id: "genshin-1",
        title: "How Genshin Impact Pity Works (Simple 2026 Guide)",
        slug: "genshin-pity-system-explained",
        game: "genshin",
        type: "Gacha Guide",
        excerpt: "Learn how the Genshin Impact Pity system works. We explain soft pity, hard pity, and the 50/50 rule in simple terms for beginners to save Primogems.",
        publishedAt: "2026-03-31",
        author: "BlueBuff Pro",
        readingTime: "12 min read",
        image: "/blog/genshin/genshin-pity-v2.png",
        featured: true,
        keywords: ["Genshin Impact Pity System Explained", "Genshin 50/50 rule", "soft pity genshin luck", "genshin primogem top-up India", "hard pity count genshin"],
        tags: ["Genshin Pity", "50/50 Rule", "Soft Pity", "Genshin Guide", "Save Primogems"]
    },
    {
        id: "genshin-2",
        title: "Increase Adventure Rank Fast in Genshin Impact (Guide)",
        slug: "genshin-increase-ar-fast",
        game: "genshin",
        type: "AR Leveling",
        excerpt: "Stuck at low AR? Learn the fastest ways to level up your Adventure Rank in Genshin Impact. We cover commissions, Resin, quests, and exploration tricks.",
        publishedAt: "2026-03-31",
        author: "BlueBuff Pro",
        readingTime: "10 min read",
        image: "/blog/genshin/genshin-ar-fast.png",
        featured: false,
        keywords: ["increase adventure rank fast genshin", "fastest way to level up genshin impact", "genshin ar exp guide", "genshin primogem recharge india", "unlock world level fast genshin"],
        tags: ["Genshin AR Fast", "Level Up Genshin", "Adventure Rank Guide", "Daily Commissions", "Genshin Resin"]
    },
    {
        id: "genshin-3",
        title: "How to Unlock Inazuma in Genshin Impact (Step by Step)",
        slug: "how-to-unlock-inazuma-genshin",
        game: "genshin",
        type: "Quest Guide",
        excerpt: "Trying to reach the Electro nation? Here is the complete step-by-step guide to unlocking Inazuma in Genshin Impact, including required Adventure Rank and quests.",
        publishedAt: "2026-03-31",
        author: "BlueBuff Pro",
        readingTime: "8 min read",
        image: "/blog/genshin/genshin-inazuma-unlock.png",
        featured: false,
        keywords: ["how to unlock inazuma genshin", "genshin impact inazuma unlock quest", "reach inazuma step by step", "ar levels for inazuma", "inazuma archon quest guide"],
        tags: ["Unlock Inazuma", "Genshin Impact Guide", "Inazuma Quest", "Adventure Rank 30", "Autumn Winds"]
    },
    {
        id: "genshin-4",
        title: "Are Genesis Crystals Worth It in Genshin Impact? (2026)",
        slug: "is-buying-genesis-crystals-worth-it",
        game: "genshin",
        type: "Value Guide",
        excerpt: "Wondering if buying Genesis Crystals is worth your money? We break down the math, Top-Up Center bonuses, Welkin Moon, and the best ways to get Primogems.",
        publishedAt: "2026-03-31",
        author: "BlueBuff Pro",
        readingTime: "9 min read",
        image: "/blog/genshin/genshin-crystal-value.png",
        featured: false,
        keywords: ["is buying genesis crystals worth it", "genshin impact primogem value", "welkin moon vs genesis crystals", "genshin double bonus reset", "buy genesis crystals india"],
        tags: ["Genesis Crystals", "Genshin Top-Up", "Primogems Guide", "Welkin Moon", "Genshin Shop"]
    },
    {
        id: "genshin-5",
        title: "How to Farm Primogems Fast in Genshin Impact (2026)",
        slug: "how-to-farm-primogems-fast",
        game: "genshin",
        type: "Farming Guide",
        excerpt: "Need Primogems quickly? Learn the absolute fastest ways to farm Primogems in Genshin Impact, from Spiral Abyss to daily commissions and exploration.",
        publishedAt: "2026-03-31",
        author: "BlueBuff Pro",
        readingTime: "11 min read",
        image: "/blog/genshin/genshin-primogem-farm.png",
        featured: false,
        keywords: ["how to farm primogems fast", "genshin impact daily primogems", "spiral abyss primogem rewards", "genshin promo codes", "fastest way to get wishes genshin"],
        tags: ["Farm Primogems", "Genshin Primogem Guide", "Fast Primogems", "Spiral Abyss", "Genshin F2P"]
    },
    {
        id: "genshin-6",
        title: "All Active Genshin Impact Redeem Codes (2026)",
        slug: "all-active-genshin-impact-redeem-codes",
        game: "genshin",
        type: "Redeem Codes",
        excerpt: "Get the latest active Genshin Impact promo codes for free Primogems, Mora, and Hero's Wits. We update this list daily so you never miss a free reward.",
        publishedAt: "2026-03-31",
        author: "BlueBuff Pro",
        readingTime: "4 min read",
        image: "/blog/genshin/genshin-redeem-codes.png",
        featured: true,
        keywords: ["genshin impact redeem codes march 2026", "active genshin codes 60 primogems", "how to redeem codes genshin", "genshin impact promo codes List", "free primogems code genshin"],
        tags: ["Genshin Impact Codes", "Genshin Promo Codes", "Free Primogems", "Genshin Redeem Codes", "Genshin Rewards"]
    }
];

