import { BlogPost } from "./types";

export const HOK_BLOGS_DATA: BlogPost[] = [
  {
    id: "hok-1",
    title: "Honor of Kings India Launch: Reviews & Performance (2026)",
    slug: "hok-india-launch-review-2026",
    game: "hok",
    type: "News",
    excerpt: "Is Honor of Kings the next big MOBA in India? We review the 2026 launch performance, server ping, player reception, and what it means for Indian esports.",
    publishedAt: "2026-03-29",
    author: "BlueBuff News",
    readingTime: "5 min read",
    image: "/blog/hok/hok-launch.png",
    featured: true,
    keywords: ["honor of kings india launch", "is hok good in india 2026", "competitive mobile gaming"],
    tags: ["HoK India Launch", "Honor of Kings Review", "Mobile Esports India", "HoK Server Ping", "Mobile MOBA"],
  },
  {
    id: "hok-2",
    title: "HoK Token Value Guide: Get More Skins for Less",
    slug: "hok-token-value-best-bundles",
    game: "hok",
    type: "Value Guide",
    excerpt: "Stop overpaying for Honor of Kings skins! Learn the exact math behind HoK Token packs, Weekly Cards, and how to get the most value for your money in 2026.",
    publishedAt: "2026-03-29",
    author: "Token Specialist",
    readingTime: "4 min read",
    image: "/blog/hok/hok-value.png",
    featured: true,
    keywords: ["best value hok tokens", "cheap hok tokens india", "buy honor of kings skins"],
    tags: ["HoK Tokens", "Honor of Kings Top Up", "HoK Weekly Card", "Cheap HoK Tokens", "HoK Skin Guide"],
  },
  {
    id: "hok-3",
    title: "HoK Jungle Guide: How to Move and Win (2026)",
    slug: "hok-jungle-strategy-pro-guide",
    game: "hok",
    type: "Strategy Guide",
    excerpt: "Master the Jungle role in Honor of Kings! Learn the best jungle rotations, how to secure objectives, and how to carry your team to victory in 2026.",
    publishedAt: "2026-03-29",
    author: "Pro Player 'Kuro'",
    readingTime: "8 min read",
    image: "/blog/hok/hok-jungle.png",
    featured: false,
    keywords: ["hok jungle guide 2026", "honor of kings map control", "how to carry in hok", "hok macro strategy"],
    tags: ["HoK Jungle Guide", "Honor of Kings Strategy", "Jungle Pathing HoK", "HoK Map Control", "Carry in HoK"],
  },
];
