import { BlogPost } from "./types";

export const MLBB_BLOGS_DATA: BlogPost[] = [
  {
    id: "mlbb-1",
    title: "MLBB Meta Tier List: Best Heroes for Solo Rank March 2026",
    slug: "mlbb-meta-tier-list-march-2026",
    game: "mlbb",
    type: "Tier List",
    excerpt:
      "Looking for the best hero to carry your team? Our latest MLBB Tier List for March 2026 covers the top meta picks that will help you reach Mythic Immortal in record time.",
    publishedAt: "2026-03-29",
    author: "Expert Player 'Axel'",
    authorRole: "Expert Player",
    readingTime: "8 min read",
    image: "/blog/mlbb-meta.png",
    featured: true,
    keywords: ["mlbb meta tier list march 2026", "best heroes for solo rank mlbb", "reach mythic immortal mlbb", "cheap mlbb diamond top-up india", "mlbb recharge india upi"],
    tags: ["Tier List", "Meta", "Ranking", "Solo Rank"],
  },
  {
    id: "mlbb-2",
    title: "How to Master the Honor of Kings x MLBB Crossover Event",
    slug: "mlbb-hok-crossover-event-guide",
    game: "mlbb",
    type: "Event Guide",
    excerpt:
      "The HOK x MLBB crossover is live! Learn how to unlock exclusive skins, participate in limited-time events, and get the most out of this massive collaboration.",
    publishedAt: "2026-03-29",
    author: "Admin",
    authorRole: "Event Specialist",
    readingTime: "5 min read",
    image: "/blog/mlbb-hok.png",
    featured: true,
    keywords: ["mlbb x hok crossover", "honor of kings mlbb skins", "unlock rewards 2026"],
    tags: ["Event", "Skins", "Guide"],
  },
  {
    id: "mlbb-3",
    title: "The Ultimate Guide to Cheap MLBB Diamond Top-Ups in India",
    slug: "cheap-mlbb-diamond-top-up-india-2026",
    game: "mlbb",
    type: "Guide",
    excerpt:
      "Finding it hard to top up diamonds in India? We provide a step-by-step guide to the safest and cheapest top-up methods available in 2026.",
    publishedAt: "2026-03-28",
    author: "Safety First",
    readingTime: "6 min read",
    image: "/blog/mlbb-recharge.png",
    featured: false,
    keywords: ["cheap mlbb diamonds india", "how to topup mlbb after ban", "safe recharge 2026"],
    tags: ["Ranking", "Pricing", "Savings"],
  },
  {
    id: "mlbb-4",
    title: "Stop Throwing Games! 5 Common Mistakes even Pro MLBB Players Make",
    slug: "mlbb-avoid-common-mistakes-to-win",
    game: "mlbb",
    type: "Game Tips",
    excerpt:
      "Are you losing games you should have won? We break down the top 5 mistakes that keep players stuck in lower ranks and how you can fix them today.",
    publishedAt: "2026-03-27",
    author: "Coach Zen",
    authorRole: "Game Expert",
    readingTime: "7 min read",
    image: "/blog/mlbb-mistakes.png",
    featured: false,
    keywords: ["mlbb gameplay tips", "fix losing streaks mlbb", "pro strategies 2026"],
    tags: ["Gameplay", "Full Guide", "How to Play"],
  },
];
