import { BlogPost } from "./types";

export const MLBB_BLOGS_DATA: BlogPost[] = [
  {
    id: "mlbb-1",
    title: "MLBB Meta Tier List: Best Heroes for Solo Rank (2026)",
    slug: "mlbb-meta-tier-list-july-2026",
    game: "mlbb",
    type: "Tier List",
    excerpt: "Climb to Mythic Immortal fast with our complete MLBB Meta Tier List for Solo Rank. Discover the most overpowered assassins, mages, and marksmen for July 2026.",
    publishedAt: "2026-03-29",
    author: "Expert Player 'Axel'",
    authorRole: "Expert Player",
    readingTime: "8 min read",
    image: "/blog/mlbb/mlbb-meta.png",
    featured: true,
    keywords: ["mlbb meta tier list july 2026", "best heroes for solo rank mlbb", "reach mythic immortal mlbb", "cheap mlbb diamond top-up india", "mlbb recharge india upi"],
    tags: ["MLBB Tier List", "Solo Rank MLBB", "Mobile Legends Meta", "Mythic Immortal", "Best MLBB Heroes"],
  },
  {
    id: "mlbb-2",
    title: "Honor of Kings x MLBB Crossover Event Guide (2026)",
    slug: "mlbb-hok-crossover-event-guide",
    game: "mlbb",
    type: "Event Guide",
    excerpt: "Master the biggest MOBA crossover of the decade! Learn how to unlock exclusive skins, farm event tokens, and maximize your rewards in the HoK x MLBB event.",
    publishedAt: "2026-03-29",
    author: "Admin",
    authorRole: "Event Specialist",
    readingTime: "5 min read",
    image: "/blog/mlbb/mlbb-hok.png",
    featured: true,
    keywords: ["mlbb x hok crossover", "honor of kings mlbb skins", "unlock rewards 2026"],
    tags: ["HoK x MLBB Event", "Honor of Kings Crossover", "MLBB Exclusive Skins", "HoK Tokens Guide", "Mobile Legends Event"],
  },
  {
    id: "mlbb-3",
    title: "Cheap MLBB Diamond Top-Ups in India (2026 Guide)",
    slug: "cheap-mlbb-diamond-topup-india-guide",
    game: "mlbb",
    type: "Top-Up Guide",
    excerpt: "Looking for cheap and safe MLBB diamonds in India? Learn how to top-up Mobile Legends diamonds using UPI, avoid scams, and secure your account.",
    publishedAt: "2026-03-29",
    author: "Admin",
    authorRole: "Top-Up Specialist",
    readingTime: "7 min read",
    image: "/blog/mlbb/mlbb-diamonds.png",
    featured: false,
    keywords: ["cheap mlbb diamonds india", "buy mlbb diamonds upi", "mlbb recharge safely", "mobile legends top up inr", "mlbb diamond store 2026"],
    tags: ["MLBB Diamonds India", "Cheap MLBB Top Up", "Mobile Legends UPI", "Safe Diamond Recharge", "MLBB India Guide"],
  },
  {
    id: "mlbb-4",
    title: "5 Mistakes Throwing Your MLBB Games (And How to Stop)",
    slug: "mlbb-avoid-common-mistakes-to-win",
    game: "mlbb",
    type: "Tips & Tricks",
    excerpt: "Stop losing winning games! Discover the 5 most common mistakes even Mythic Mobile Legends players make, from map awareness to poor drafting.",
    publishedAt: "2026-03-28",
    author: "Safety First",
    readingTime: "6 min read",
    image: "/blog/mlbb/mlbb-mistakes.png",
    featured: false,
    keywords: ["mlbb mistakes to avoid", "how to win solo queue mlbb", "mobile legends guide 2026", "anti heal mlbb"],
    tags: ["MLBB Mistakes", "Mobile Legends Tips", "How to Win MLBB", "Mythic Rank Guide", "Stop Throwing MLBB"],
  },
  {
    id: "mlbb-5",
    title: "Top 10 MLBB Hero Skins & Price List in India (2026)",
    slug: "mlbb-skin-price-list-india-2026",
    game: "mlbb",
    type: "Game Guide",
    excerpt: "Discover the ultimate list of the best Mobile Legends skins in 2026! We break down the exact Diamond costs and INR prices for Elite, Epic, and Collector skins.",
    publishedAt: "2026-06-23",
    author: "Admin",
    authorRole: "Gaming Specialist",
    readingTime: "7 min read",
    image: "/blog/mlbb/mlbb-skin-price-banner.png",
    featured: true,
    keywords: ["mlbb skin price list india 2026", "mobile legends skins inr", "mlbb epic skin cost", "collector skin price mlbb"],
    tags: ["MLBB Skins", "Mobile Legends Price List", "MLBB India Pricing", "Epic Skins", "Collector Skins"],
  },
  {
    id: "mlbb-6",
    title: "How to Get Free MLBB Diamonds in India 2026 (Legit Ways)",
    slug: "free-mlbb-diamonds-india-2026-legit-methods",
    game: "mlbb",
    type: "Tips & Tricks",
    excerpt: "Want free MLBB diamonds in India? Discover the only 100% legitimate methods to earn diamonds in 2026 without risking a ban. Avoid scams with our full guide!",
    publishedAt: "2026-06-23",
    author: "Admin",
    authorRole: "Gaming Specialist",
    readingTime: "8 min read",
    image: "/blog/mlbb/free-mlbb-diamonds-banner.png",
    featured: true,
    keywords: ["free mlbb diamonds 2026", "how to get free diamonds mobile legends", "free mlbb diamonds india", "legit free diamonds mlbb"],
    tags: ["Free Diamonds", "MLBB Scams to Avoid", "Mobile Legends Guide", "Promo Diamonds", "MLBB Top Up India"],
  },
  {
    id: "mlbb-7",
    title: "Top 10 Indian MLBB Streamers & YouTubers to Watch in 2026",
    slug: "top-10-indian-mlbb-streamers-2026",
    game: "mlbb",
    type: "Community",
    excerpt: "Discover the Top 10 Indian Mobile Legends (MLBB) streamers and YouTubers in 2026. Improve your gameplay, learn the meta, and enjoy top-tier entertainment!",
    publishedAt: "2026-06-23",
    author: "Admin",
    authorRole: "Gaming Specialist",
    readingTime: "7 min read",
    image: "/blog/mlbb/top-10-indian-streamers-banner.png",
    featured: true,
    keywords: ["indian mlbb streamers", "top mlbb youtubers india", "learn mlbb from pros", "mobile legends india 2026"],
    tags: ["Indian Streamers", "MLBB Community", "Esports India", "Mobile Legends Guides", "Pro Gameplay"],
  },
  {
    id: "mlbb-8",
    title: "How to Play MLBB on PC Free in India 2026 — BlueStacks Setup Guide",
    slug: "how-to-play-mlbb-on-pc-india-2026",
    game: "mlbb",
    type: "Tech Guide",
    excerpt: "Want to play Mobile Legends on PC? Discover the ultimate 2026 guide to downloading and setting up MLBB on BlueStacks for free in India. Enhance your gameplay today!",
    publishedAt: "2026-06-23",
    author: "Admin",
    authorRole: "Tech Specialist",
    readingTime: "8 min read",
    image: "/blog/mlbb/mlbb-pc-bluestacks-banner.png",
    featured: true,
    keywords: ["how to play mlbb on pc", "mobile legends bluestacks guide", "mlbb pc setup 2026", "mlbb emulator free"],
    tags: ["PC Guide", "BlueStacks Setup", "MLBB Emulator", "Tech Guide", "Mobile Legends PC"],
  },
  {
    id: "mlbb-9",
    title: "Best Phone Under ₹15,000 for MLBB in India 2026 (60 FPS Tested)",
    slug: "best-phone-under-15000-mlbb-india-2026",
    game: "mlbb",
    type: "Hardware Review",
    excerpt: "Looking for the best budget gaming phone? Discover the top smartphones under ₹15,000 in India that can run Mobile Legends (MLBB) at a smooth 60 FPS in 2026.",
    publishedAt: "2026-06-23",
    author: "Admin",
    authorRole: "Tech Specialist",
    readingTime: "9 min read",
    image: "/blog/mlbb/mlbb-budget-phone-banner.png",
    featured: true,
    keywords: ["best phone under 15000 for mlbb", "budget gaming phone india 2026", "mlbb 60 fps phone", "poco x6 neo mlbb test"],
    tags: ["Budget Gaming Phone", "Mobile Legends 60 FPS", "Phone Review", "Gaming Hardware", "MLBB Performance"],
  },
  {
    id: "mlbb-10",
    title: "Is MLBB Starlight Member Worth It in India? Honest 2026 Review",
    slug: "mlbb-starlight-member-worth-it-india-2026",
    game: "mlbb",
    type: "Game Review",
    excerpt: "Thinking about buying the MLBB Starlight Membership in India? Read our honest 2026 review breaking down the exact diamond value, rewards, and whether it's worth your money.",
    publishedAt: "2026-06-23",
    author: "Admin",
    authorRole: "Gaming Specialist",
    readingTime: "7 min read",
    image: "/blog/mlbb/mlbb-starlight-banner.png",
    featured: true,
    keywords: ["mlbb starlight worth it", "starlight membership india 2026", "mobile legends starlight rewards", "starlight cost india"],
    tags: ["Starlight Member", "MLBB Review", "Mobile Legends Guide", "Diamond Value", "Starlight Rewards"],
  },
];
