import { BlogPost } from "./types";

export const MLBB_BLOGS_DATA: BlogPost[] = [
  {
    id: "mlbb-1",
    title: "MLBB Meta Tier List: Best Heroes for Solo Rank (2026)",
    slug: "mlbb-meta-tier-list-july-2026",
    game: "mlbb",
    type: "Tier List",
    excerpt: "Climb to Mythic Immortal fast with our complete MLBB Meta Tier List for Solo Rank. Discover the most overpowered assassins, mages, and marksmen for July 2026.",
    publishedAt: "2026-03-29",
    author: "Expert Player 'Axel'",
    authorRole: "Expert Player",
    readingTime: "8 min read",
    image: "/blog/mlbb/mlbb-meta.png",
    featured: true,
    keywords: ["mlbb meta tier list july 2026", "best heroes for solo rank mlbb", "reach mythic immortal mlbb", "cheap mlbb diamond top-up india", "mlbb recharge india upi"],
    tags: ["MLBB Tier List", "Solo Rank MLBB", "Mobile Legends Meta", "Mythic Immortal", "Best MLBB Heroes"],
  },
  {
    id: "mlbb-2",
    title: "Honor of Kings x MLBB Crossover Event Guide (2026)",
    slug: "mlbb-hok-crossover-event-guide",
    game: "mlbb",
    type: "Event Guide",
    excerpt: "Master the biggest MOBA crossover of the decade! Learn how to unlock exclusive skins, farm event tokens, and maximize your rewards in the HoK x MLBB event.",
    publishedAt: "2026-03-29",
    author: "Admin",
    authorRole: "Event Specialist",
    readingTime: "5 min read",
    image: "/blog/mlbb/mlbb-hok.png",
    featured: true,
    keywords: ["mlbb x hok crossover", "honor of kings mlbb skins", "unlock rewards 2026"],
    tags: ["HoK x MLBB Event", "Honor of Kings Crossover", "MLBB Exclusive Skins", "HoK Tokens Guide", "Mobile Legends Event"],
  },
  {
    id: "mlbb-3",
    title: "Cheap MLBB Diamond Top-Ups in India (2026 Guide)",
    slug: "cheap-mlbb-diamond-topup-india-guide",
    game: "mlbb",
    type: "Top-Up Guide",
    excerpt: "Looking for cheap and safe MLBB diamonds in India? Learn how to top-up Mobile Legends diamonds using UPI, avoid scams, and secure your account.",
    publishedAt: "2026-03-29",
    author: "Admin",
    authorRole: "Top-Up Specialist",
    readingTime: "7 min read",
    image: "/blog/mlbb/mlbb-diamonds.png",
    featured: false,
    keywords: ["cheap mlbb diamonds india", "buy mlbb diamonds upi", "mlbb recharge safely", "mobile legends top up inr", "mlbb diamond store 2026"],
    tags: ["MLBB Diamonds India", "Cheap MLBB Top Up", "Mobile Legends UPI", "Safe Diamond Recharge", "MLBB India Guide"],
  },
  {
    id: "mlbb-4",
    title: "5 Mistakes Throwing Your MLBB Games (And How to Stop)",
    slug: "mlbb-avoid-common-mistakes-to-win",
    game: "mlbb",
    type: "Tips & Tricks",
    excerpt: "Stop losing winning games! Discover the 5 most common mistakes even Mythic Mobile Legends players make, from map awareness to poor drafting.",
    publishedAt: "2026-03-28",
    author: "Safety First",
    readingTime: "6 min read",
    image: "/blog/mlbb/mlbb-mistakes.png",
    featured: false,
    keywords: ["mlbb mistakes to avoid", "how to win solo queue mlbb", "mobile legends guide 2026", "anti heal mlbb"],
    tags: ["MLBB Mistakes", "Mobile Legends Tips", "How to Win MLBB", "Mythic Rank Guide", "Stop Throwing MLBB"],
  },
];
